Add user client certificate validation capabiltiy
qdrant/qdrant pull request #1663
Opened 2023-04-05 02:02 UTC by DengYiping

- Add capability to validate user client's certificate. This is used to ensure only authorized user can access the HTTPs API and gRPC service

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally using ``cargo fmt`` command prior to submission?
3. [x] Have you checked your code using ```cargo clippy``` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-04-05 07:14 UTC, timvisee requested changes
Thanks for his contribution.

It does seem the TLS is failing though, even though you've set to use the local cert/key. Could you investigate this further?

```
 curl: (56) OpenSSL SSL_read: OpenSSL/1.1.1t: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca, errno 0
```

2023-04-06 02:35 UTC, DengYiping commented
I noticed this failure on the new build. I think it is completely unrelated
> Integration tests / test-consensus (pull_request) Failing after 15m

2023-04-06 07:03 UTC, timvisee approved these changes
LGTM!

Don't worry about the failed test, consensus is flaky sometimes.

I've simplified setting the SSL verify mode a bit on your branch because it was quite verbose.

2023-04-06 07:39 UTC, generall approved these changes

2023-04-06 12:51 UTC, DengYiping commented
> I've simplified setting the SSL verify mode a bit on your branch because it was quite verbose.

Thanks!

2023-04-07 10:54 UTC, DengYiping commented
Anyone mind merging this?

2023-04-10 14:03 UTC, merged