Draft: optional named vectors
qdrant/qdrant pull request #1724
Opened 2023-04-13 13:49 UTC by timvisee

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally using ``cargo fmt`` command prior to submission?
3. [ ] Have you checked your code using ```cargo clippy``` command?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2023-04-14 13:45 UTC, timvisee commented on lib/segment/src/vector_storage/memmap_vector_storage.rs
> +        for id in deleted_ids {
When updating mmap storage from another, we first insert new vectors in a loop, then we process all deletions in a second loop. I find this ugly, but I don't see a way to do this more elegantly. Is it good enough?

2023-04-14 13:45 UTC, timvisee commented on lib/segment/src/vector_storage/mmap_vectors.rs
> +unsafe fn mmap_to_bitslice<'a>(mmap: &mut MmapMut) -> &'a mut BitSlice {
@IvanPleshkov @generall Maybe look at this in a bit more detail to make sure it is sound.

2023-04-17 10:53 UTC, IvanPleshkov approved these changes

2023-04-17 12:06 UTC, generall requested changes
- flush for mmap storage
- other changes as discussed in a call

2023-04-17 13:09 UTC, timvisee commented
I've implemented the discussed changes.

See these commits: 566153b3d7b011231cbb91f934a962c6493a47fe...bf6e3e2a5fa2310997768831a088654919a031ef

2023-04-17 13:09 UTC, timvisee commented on lib/segment/src/vector_storage/memmap_vector_storage.rs
> +        for id in deleted_ids {
We discussed this in a call; this is okay.

2023-04-19 08:07 UTC, generall approved these changes

2023-04-20 10:06 UTC, merged