feat: Allow running without config specified
qdrant/qdrant pull request #1773
Opened 2023-04-23 00:16 UTC by paulotten

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally using `cargo fmt` command prior to submission?
3. [ ] Have you checked your code using `cargo clippy` command?

2023-04-23 00:17 UTC, paulotten commented
Two tests failing locally. Investigating.

2023-04-23 00:22 UTC, paulotten commented
> Two tests failing locally. Investigating.

Fixed. `test_default_config()` was setting `RUN_MODE` to "TEST", which is invalid.

2023-04-23 01:09 UTC, paulotten commented
@generall 

It looks like I need to update openapi specifications (and probably gRPC .proto files). Does this sound right?

Before I go making changes there, does what I've changed so far look good?

2023-04-24 07:49 UTC, timvisee requested changes
Thanks for your contribution!

No logic problems. I do have some nitpicks though, please see my comments.

Could you also [update](https://github.com/qdrant/qdrant/blob/master/docs/DEVELOPMENT.md#rest) the OpenAPI specification to apply these changes?

2023-04-24 07:49 UTC, timvisee commented on lib/collection/src/optimizers_builder.rs
> +fn default_deleted_threshold() -> f64 {
`const fn` + 5 others below

2023-04-24 07:49 UTC, timvisee commented on src/settings.rs
> +fn default_service_host() -> String {
`const fn` + 3 others below

2023-04-24 07:49 UTC, timvisee commented on src/settings.rs
> +fn default_p2p_port() -> Option<u16> {
`const fn` + 3 others below

2023-04-24 08:36 UTC, timvisee commented
Before continuing work on this, please see: https://github.com/qdrant/qdrant/issues/1771#issuecomment-1519627674

2023-04-28 08:28 UTC, timvisee commented
Closing this because <https://github.com/qdrant/qdrant/pull/1776> is merged (which is an alternative).

Feel free to open this again if you think there is a good reason for it.

2023-04-28 08:28 UTC, closed without merging