fix: panic cargo bench on lib/segment
qdrant/qdrant pull request #1958
Opened 2023-05-24 10:56 UTC by 9bany

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo fmt` command prior to submission?
3. [x] Have you checked your code using `cargo clippy` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
### Description 
Re: pull request https://github.com/qdrant/qdrant/pull/1952

2023-06-01 12:31 UTC, timvisee approved these changes

2023-06-12 08:06 UTC, agourlay requested changes
see previous comment

2023-09-29 12:01 UTC, IvanPleshkov approved these changes

2023-09-29 12:13 UTC, IvanPleshkov requested changes
The fix should be more complicated. In this fix FakeMetric didn't applied in raw scorer

2023-10-02 09:44 UTC, IvanPleshkov commented
I propose to remove Fake Metric at all: https://github.com/qdrant/qdrant/pull/2754

2023-10-02 11:30 UTC, closed without merging