fix usage of try_reserve_exact
qdrant/qdrant pull request #2286
Opened 2023-07-18 23:26 UTC by generall

This PR fixes usage of `try_reserve_exact` function in chunked vectors which leads to over-allocation.

Rust really should allow specifying param names during function calls.
This naming is very confusing, no wonder this happened.

ToDo: check for other places where `try_reserve_exact` or `try_reserve` is used

2023-07-19 08:41 UTC, IvanPleshkov approved these changes

2023-07-19 08:41 UTC, IvanPleshkov commented on lib/segment/src/index/hnsw_index/graph_links.rs
> +        let additional_capacity = link_slice.len().saturating_sub(links.capacity());
I'm not sure that changes in this file are necessary. `try_reverse_exact` is called here for empty vector, so there is no matter, does it require capacity or additional size.

2023-07-19 08:46 UTC, ffuugoo requested changes
Should we make an utility function that would calculate "additional capacity" and call `try_reserve_exact`? It's literally copied 7 times in this PR...

I think we can call this utility function `try_set_capacity`? (And also rename `try_reserve_size` method.) I think this way it would cause less confusion.

Other than that, LGTM. I also fuck up with `reserve` methods pretty much all the time, because they _add additional_ capacity, rather _set_ it to an absolute value.

2023-07-19 09:30 UTC, generall commented
@ffuugoo fixed

2023-07-19 09:54 UTC, ffuugoo approved these changes
LGTM. 👌

2023-07-19 09:56 UTC, merged

2023-07-24 08:04 UTC, timvisee commented
Good catch. Thanks for trait-ing this!