Shutdown on conflicting interface ports
qdrant/qdrant pull request #2611
Opened 2023-09-07 14:14 UTC by agourlay

This PR is done in the context of https://github.com/qdrant/qdrant/issues/2610 but does not solve the issue yet.

Currently the server boots up successfully even if the HTTP or/and gRPC ports are already used.

The only hint for the operator is a single log line and it is even more confusing if one of the port is correct.

With this PR, the server simply refuses to start if it detects any port conflicts.

Given that the servers gets started in different threads, it is pretty difficult to catch the error without waiting.

The proposed solution is to check the port just before starting the respective servers.

e.g.

```
2023-09-07T13:56:48.078936Z  INFO storage::content_manager::consensus::persistent: Loading raft state from ./storage/raft_state.json    
2023-09-07T13:56:48.079517Z DEBUG storage::content_manager::consensus::persistent: State: Persistent { state: RaftState { hard_state: HardState { term: 0, vote: 0, commit: 0 }, conf_state: ConfState { voters: [4189242522808721], learners: [], voters_outgoing: [], learners_next: [], auto_leave: false } }, latest_snapshot_meta: SnapshotMetadataSer { term: 0, index: 0 }, apply_progress_queue: EntryApplyProgressQueue(None), peer_address_by_id: RwLock { data: {} }, this_peer_id: 4189242522808721, path: "./storage/raft_state.json", dirty: false }    
2023-09-07T13:56:48.085531Z  INFO qdrant: Distributed mode disabled    
2023-09-07T13:56:48.085631Z  INFO qdrant: Telemetry reporting disabled    
2023-09-07T13:56:48.085706Z ERROR qdrant::ports: Could not start REST server because the port 8000 is already in use    
Error: Could not start REST server because the port 8000 is already in use
agourlay@agourlay-thinkpad:~/Workspace/qdrant$ echo $?
1

```

2023-09-08 11:44 UTC, timvisee requested changes
I don't think this check is sufficient. A race condition is possible in between the check and actual binding.

Would it be possible to catch the 'port already in use' message from where we currently bind instead?

2023-09-08 12:39 UTC, agourlay commented
> Would it be possible to catch the 'port already in use' message from where we currently bind instead?

I tried but

> Given that the servers gets started in different threads, it is pretty difficult to catch the error without waiting.

Not sure how to do this cleanly TBH.

The main thread would have to wait until the server is fully started by probing the API?

2023-09-08 13:19 UTC, timvisee commented
> > Would it be possible to catch the 'port already in use' message from where we currently bind instead?
> 
> I tried but
> 
> > Given that the servers gets started in different threads, it is pretty difficult to catch the error without waiting.
> 
> Not sure how to do this cleanly TBH.
> 
> The main thread would have to wait until the server is fully started by probing the API?

Can't we catch the error asynchronously, and trigger a shutdown in the same place we handle SIGTERMs?

2023-09-10 10:14 UTC, generall commented on src/ports.rs
> +    if check_port_available(port) {
Possible TOCTOU problem here:

https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use

2023-09-11 07:30 UTC, closed without merging