Fix `test_building_cancellation` flakiness with larger base segment
qdrant/qdrant pull request #2697
Opened 2023-09-19 09:11 UTC by timvisee

Fixes <https://github.com/qdrant/qdrant/issues/2695>.

Similar to <https://github.com/qdrant/qdrant/pull/2682>, but with 5k points as 2k was not large enough.

The `test_building_cancellation` test flaky. It depends on timings which are currently too close together causing false negatives.

This multiplies the number of points for the test collection by 5, increasing the difference between the timings, reducing flakiness.

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

2023-09-19 11:55 UTC, coszio requested changes

2023-09-19 11:55 UTC, coszio commented on lib/segment/tests/integration/segment_builder_test.rs
> +    let (time_baseline, was_cancelled_baseline) = estimate_build_time(&baseline_segment, 20000);
Looks like we need to re-increase this timeout now.

2023-09-19 12:45 UTC, coszio commented
Just realized now baseline is not the problem. The assertion failure is when comparing early vs later stop times.

I am thinking of using more delay between early/later cancellation instead

2023-09-19 13:32 UTC, agourlay commented
I have a bit of a provocative question :)

Do we actually need this test?

2023-09-19 14:35 UTC, coszio commented
I have no objection against it, I just feel like we were not testing it correctly.

2023-09-19 14:35 UTC, coszio approved these changes

2023-09-19 16:42 UTC, coszio commented
@timvisee it does this already, plus makes sure that it can also be cancelled at a later stage. I guess this is the source of complexity right now.

2023-09-20 06:44 UTC, agourlay commented on lib/segment/tests/integration/segment_builder_test.rs
> +    dbg!(time_baseline);
want to keep the debug statement?

2023-09-20 07:42 UTC, timvisee commented on lib/segment/tests/integration/segment_builder_test.rs
> +    dbg!(time_baseline);
Not needed. I'll remove it.

2023-09-20 08:41 UTC, agourlay approved these changes
Let's give this a try :+1: 

I will for sure ask again if we need this test in the next flaky PR :grin:

2023-09-20 08:56 UTC, merged