Validate sparse indices in grpc search
qdrant/qdrant pull request #3225
Opened 2023-12-13 17:55 UTC by IvanPleshkov

Add custom validation step in grpc while conversion. We cannot use default field-based validation because sparse requests require checking 2 separate fields. I find the custom implementation of struct validation bad because It affects another validated field.

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-12-14 10:45 UTC, agourlay commented
Can you please add a quick test for the new validation in `basic_sparse_grpc_test.sh` to make sure that it works :)

2024-01-11 09:51 UTC, agourlay requested changes
needs a test :)

2024-02-12 09:01 UTC, agourlay approved these changes

2024-02-12 09:08 UTC, timvisee commented on lib/api/build.rs
Can we also implement actual validation here, instead of doing validation on conversion?

I know it's somewhat annoying to do here, but it's where we do it for everything else as well.

See some examples here: https://github.com/qdrant/qdrant/blob/33094335dd06040d325946e66afd079afcb98b32/lib/api/src/grpc/validate.rs

2024-02-12 09:28 UTC, IvanPleshkov commented on lib/api/build.rs
We have one:
https://github.com/qdrant/qdrant/blob/33094335dd06040d325946e66afd079afcb98b32/lib/api/src/grpc/validate.rs#L195
If you find an additional check on vector conversion wrong, mark please PR as `request changes`

2024-02-12 09:45 UTC, timvisee commented on lib/api/build.rs
You're totally right. Thanks!

2024-02-12 09:45 UTC, timvisee approved these changes

2024-02-12 09:45 UTC, merged