add: debian package build step
qdrant/qdrant pull request #3341
Opened 2024-01-05 22:41 UTC by neo773

This PR adds build step for Debian package.

Tested on Debian 12
<img width="1051" alt="SCR-20240106-ehgf" src="https://github.com/qdrant/qdrant/assets/62795688/e77f827b-3c8c-444f-a6bb-dea066cac755">

/claim #3340

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

2024-01-05 23:20 UTC, generall commented on .github/workflows/release-artifacts.yml
> +          name:  ${{ matrix.target }}-debian
It looks like you are building it in `build-mac-binaries` for mac os. It should be in `build-linux-binaries`

2024-01-05 23:21 UTC, generall requested changes
Could you please trigger CI on your fork, so we could see that CI actually works and produces usable packages

2024-01-06 01:47 UTC, neo773 commented
@generall 

Successful build [here](https://github.com/neo773/qdrant/actions/runs/7428502193/job/20215913616)

<img width="514" alt="SCR-20240106-gxyh" src="https://github.com/qdrant/qdrant/assets/62795688/305b0231-7222-49aa-a83b-72e7ddb75366">

2024-01-06 21:56 UTC, generall requested changes
When I try to install it on my server, i see this error:
![image](https://github.com/qdrant/qdrant/assets/1935623/974ec6aa-9d51-4291-b7c1-10a7018912cb)

As I understood, deb can't automatically install all required dependencies.

Would it be possible to base .deb package on MUSL build from here https://github.com/qdrant/qdrant/pull/3342 to avoid errors like this?

2024-01-06 22:16 UTC, neo773 commented
Looking into MUSL, worked fine on my Ubuntu VM so I assumed it was good.

<img width="729" alt="image" src="https://github.com/qdrant/qdrant/assets/62795688/5e9e20cf-d801-4a4d-aacb-5cff0fc82a1e">

2024-01-06 23:11 UTC, neo773 commented
Pushed a new commit that uses musl, also tested the package on x86 this time.

<img width="575" alt="image" src="https://github.com/qdrant/qdrant/assets/62795688/df6e65e8-cbeb-463c-be05-22af468fdbe0">


[Release](https://github.com/neo773/qdrant/releases/tag/v1.7.10)
[CI Run](https://github.com/neo773/qdrant/actions/runs/7434325055/job/20228354047#step:7:146)

2024-01-06 23:16 UTC, neo773 commented
Sorry, I just realized I was merging into `master` instead of `dev` closing this PR as I've made a new one https://github.com/qdrant/qdrant/pull/3344

2024-01-06 23:16 UTC, closed without merging