add optional checksum to snapshot recovery request
qdrant/qdrant pull request #3381
Opened 2024-01-12 03:23 UTC by xzfc

Add `checksum` option to `RecoverShardSnapshotRequest` (GRPC), `/collections/{collection_name}/snapshots/recover`, `/collections/{collection}/shards/{shard}/snapshots/recover`, and (REST).
Closes #3371.

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-01-12 09:01 UTC, timvisee reviewed
Thank you for your effort on this! :smile: 

I've left some review comments below.

2024-01-12 09:01 UTC, timvisee commented on src/actix/api/snapshot_api.rs
We should also add a `checksum` parameter to `/collections/{name}/snapshots/upload`. It likely needs to be a query parameter in the `SnapshotUploadingParam` struct. We only have this extra endpoint in REST, not in gRPC.

2024-01-14 11:30 UTC, xzfc commented on src/actix/api/snapshot_api.rs
Added for checksum checking for `/collections/{name}/snapshots/upload` and `/collections/{collection}/shards/{shard}/snapshots/upload`.

2024-01-14 11:30 UTC, xzfc commented
Updated according to comments, please take a look.

2024-01-15 15:05 UTC, timvisee requested changes
Thanks a lot for your improvements!

I think there are two more things left to do:

1. update the OpenAPI specification, see the review comment below.
2. add a basic integration test.

Regarding the test, I imagine the simplest one to be:
- have a collection with some points
- create a snapshot, download the snapshot file
- delete the collection
- try to restore the file with a wrong hash (one different character?), assert error
- try to restore the file with correct hash, assert success
- preferably an integration test function per snapshot type (collection and shard snapshots)

You can probably add this test [here](https://github.com/qdrant/qdrant/tree/master/openapi/tests/openapi_integration), and reuse some components.

2024-01-15 15:05 UTC, timvisee commented on docs/redoc/master/openapi.json
Could you add the `checksum` parameter for the upload endpoint(s) in `openapi/openapi-snapshots.ytt.yaml` and `openapi/openapi-shard-snapshots.ytt.yaml`? Then these will be properly reflected in this schema as well once you regenerate them.

Sadly we've to define these parameters manually at this time.

2024-01-18 18:52 UTC, xzfc commented
@timvisee Done.

Initially, I did not add tests because there were no existing pytests involving downloading/uploading files.
(there is `tests/snapshots/snapshots-recovery.sh`, but it seems it is not used on CI and is not very convenient to maintain IMO)
Now, I come up with a pytest fixture to serve files from the temporary directory over HTTP.

2024-01-24 09:39 UTC, timvisee commented
Thanks! I skimmed through it just now, and everything looks sound. I'll try to do a more in-depth review later today.

I don't think starting a web server to serve the files is strictly necessary for this. You _can_ also provide an `file:///some/dir` URI to grab a snapshot file from disk. But still, it doesn't hurt to keep this in as long as it doesn't give us any flakiness. The good thing is that this now also tests downloading snapshots from an URL, which we did not cover anywhere else yet. So, I suggest to keep it like this :+1:

2024-01-25 14:08 UTC, timvisee approved these changes
Perfect! I like that you also validate the hash in Python, and that you set the HTTP server up to be a fixture.

Before we can merge, would you mind to rebase on `dev` resolving the conflicts?

2024-01-25 14:17 UTC, xzfc commented
Rebased.

2024-01-25 14:22 UTC, timvisee approved these changes
Thanks once again! :raised_hands:

2024-01-25 15:00 UTC, merged