Add "metadata" field to the shard WAL
qdrant/qdrant pull request #3408
Opened 2024-01-16 17:08 UTC by ffuugoo

__TBD__

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-01-29 13:58 UTC, generall commented on lib/collection/src/collection/point_ops.rs
> +                        operation.into(), // TODO: Assign tag!
I would prefer to use explicit conversion `WithMeta::from(operation)`, as in this case navigation and code usage search is much simpler. (yes, even with rust_analyser)

2024-01-29 14:01 UTC, generall commented on lib/collection/src/operations/mod.rs
> +impl WithMeta {
`WithMeta` looks more like a trait name. Maybe `OperationWithMeta`? 
Also `metadata` in general might be mixed up with payload. Not sure what would be a better alternative, though

2024-01-29 14:04 UTC, generall commented on lib/collection/src/operations/mod.rs
> +            let input = serde_json::to_string(&tagged).unwrap();
WAL uses `serde_cbor`, maybe worth testing with it as well?

2024-01-29 14:12 UTC, generall requested changes
Renaming + minor stuff mentioned in comments, the rest LGTM

2024-01-29 17:02 UTC, ffuugoo commented
@generall Rebased on recent `dev`, added `timestamp` field to internal point update gRPC API (from #3426), renamed `WithMeta` into `OperationWithTimestamp` and `OperationMeta` into `OperationTimestamp`.

2024-01-30 20:26 UTC, generall approved these changes

2024-01-31 14:04 UTC, ffuugoo commented
Rebased on `dev`. (Had to squash everything to simplify rebase, sorry.)

2024-01-31 14:32 UTC, ffuugoo commented
There are a few `TODO`s scattered around the code, I'll fix them up in a few hours.

2024-01-31 15:13 UTC, timvisee approved these changes
I don't like the TODOs, but I don't see a better way of doing things (assuming we cannot fix them in this PR).

2024-01-31 15:16 UTC, ffuugoo commented
> I don't like the TODOs, but I don't see a better way of doing things (assuming we cannot fix them in this PR).

Some are left there intentionally to be fixed in the follow-up PRs, so I'll fix today before merging.

2024-01-31 18:41 UTC, ffuugoo commented on lib/collection/src/shards/forward_proxy_shard.rs
> +                    // TODO: Assign clock tag!? 🤔
Well, yes, but I'd still leave it for now until we implement all parts completely. Maybe something else comes up and would be able/have to assign the tag. Having it marked with `TODO` makes it a bit easier to find/harder to overlook.

2024-02-01 09:46 UTC, timvisee commented
Great! CI is green now. I'll give you the honor to merge.

2024-02-01 10:44 UTC, merged