chore: sort the denpendencies & rm useless dependencies
qdrant/qdrant pull request #3454
Opened 2024-01-24 06:55 UTC by ben1009

### All Submissions:

* [ ] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [ ] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-01-29 09:19 UTC, timvisee commented on Cargo.toml
> +# Consensus related crates
Leaving this comment here does not make sense now.

2024-01-29 09:19 UTC, timvisee commented on Cargo.toml
>  # Profiling
Same, this is an useless comment now.

2024-01-29 12:45 UTC, generall requested changes
The benefit of sorting dependencies is kinda questionable. In current version we could have some kind of grouping.
In my opinion sorting only makes sense if we want to search faster, which doesn't look like a problem in case of cargo files.

I would only keep the "remove unused" part

2024-01-30 07:46 UTC, ben1009 commented
> The benefit of sorting dependencies is kinda questionable. In current version we could have some kind of grouping. In my opinion sorting only makes sense if we want to search faster, which doesn't look like a problem in case of cargo files.
> 
> I would only keep the "remove unused" part

get your point

- revert to run `cargo sort -g` to keep the group if any
- for sort besides search faster, another benefit is [Large projects tend to like for things to stay sorted to cut down the occurrence of merge conflicts between two developers appending to the end of the same unsorted list in parallel changes. ](https://github.com/dtolnay/request-for-implementation/issues/29)
- for the "remove unused" part, already done in https://github.com/qdrant/qdrant/pull/3435, as you can see, no cargo.lock change in this pr

2024-01-30 08:33 UTC, timvisee commented
> for sort besides search faster, another benefit is [Large projects tend to like for things to stay sorted to cut down the occurrence of merge conflicts between two developers appending to the end of the same unsorted list in parallel changes. ](https://github.com/dtolnay/request-for-implementation/issues/29)

Yes, I do like this part, but we can still do that with grouping.

Removing unused and sorting groups would be a good middle ground for me :+1:

2024-02-11 18:38 UTC, closed without merging