Feat/set payload by key
qdrant/qdrant pull request #3548
Opened 2024-02-06 12:28 UTC by Shylock-Hg

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

Close #3524
/claim #3524

2024-02-07 03:22 UTC, xzfc commented
> this assertion failed, HTTP should return error when key is empty string.
>  I can't found the reason, could give me some tips?

@Shylock-Hg By default, this endpoint responds with `HTTP 202 Accepted` immediately while running its job in the background. You need to pass `wait=true` as a query parameter to get its result/error, like this:
https://github.com/qdrant/qdrant/blob/eec5022831a2b93a8d3fd6db9072d152070fa3d7/openapi/tests/openapi_integration/test_payload_operations.py#L22

2024-02-09 12:15 UTC, generall requested changes
Hey @Shylock-Hg, thanks for the PR!
I think interface matches our expectation, however there are a few problems with internals:


Proposed API change breaks guarantee of [Idempotence](https://en.wikipedia.org/wiki/Idempotence).
In other words, sending same request twice produce different result and different state of the storage.

For example:

Assume point 123 have empty payload.  When we do:

```
POST collections/test_collection/points/payload?wait=true
{
  "points": [123],
  "payload": {
    "a": 1
  },
  "key": "nested1"
}
```

It will generate point with:

```
 "payload": {
  "a": 1
}
```

But sending the same request twice will produce:

```
"error": "Wrong input: Can't find payload key segment: \"nested1\"."
```

Having Idempotence API is critical for Qdrant's distributed deployment mode and we can't ignore it.


On top of that there are a few other problems I will highlight in followup comments.

2024-02-09 12:20 UTC, generall commented on lib/segment/src/types.rs
> +        let segs = key.split('.').collect::<Vec<&str>>();
Json path might be more complicated than that. See `get_value_from_json_map_opt`

2024-02-09 12:22 UTC, generall commented on lib/segment/src/types.rs
> +                description: format!("Unexpected payload key: \"{key}\""),
Empty `key` might be considered as "overwrite" for the whole object. In this case we are covering "overwrite" API as well.

2024-02-09 12:23 UTC, generall commented on lib/segment/src/types.rs
> +                description: format!("Can't find payload key segment: \"{seg}\"."),
I think this should create required nested object instead of faiting with error.

2024-02-09 12:24 UTC, generall commented on lib/api/src/grpc/proto/points.proto
> +  optional string key = 8; // Option for indicate property of payload
Would need to come up with better description for this field. (note mostly to myself)

2024-02-11 15:19 UTC, generall requested changes

2024-02-11 15:19 UTC, generall commented on lib/segment/src/common/utils.rs
> +pub fn set_value_to_json_map<'a>(
this function requires explicit testing

2024-02-11 15:19 UTC, generall commented on lib/segment/src/common/utils.rs
> +pub fn set_value_to_json_map<'a>(
Having openapi integration tests is nice, but it would be better to implement unit-tests here as well

2024-02-11 15:19 UTC, generall commented on lib/segment/src/payload_storage/simple_payload_storage_impl.rs
> +                self.payload.insert(point_id, payload.to_owned());
This logic path ignores `key`, that will create a situation where idempotency will not be satisfied.

2024-02-12 13:17 UTC, generall commented on lib/segment/src/payload_storage/simple_payload_storage_impl.rs
> +                self.payload.insert(point_id, payload.to_owned());
> I plan to return error in this branch

no, it is a valid request. You just need to merge empty payload with given

2024-02-12 15:05 UTC, generall commented on lib/segment/src/payload_storage/simple_payload_storage_impl.rs
> +                self.payload.insert(point_id, payload.to_owned());
same as we would expect if stored payload doesn't have `key1.key2`

2024-02-15 06:51 UTC, xzfc commented
> This linter seems wrong. I never modify related files in this PR.

@Shylock-Hg It probably was caused basing your PR on the `master` branch. You should target your PRs onto `dev`, not `master`. I've rebased your PR to `dev`.

2024-02-15 12:50 UTC, generall approved these changes
LGTM once tests are green

2024-02-15 14:15 UTC, merged