RBAC: Route `Claims` into `TableOfContent` for points API
qdrant/qdrant pull request #3801
Opened 2024-03-08 12:56 UTC by coszio

There are some claims, like `filter` and `payload` which need to access the deserialized structures from `Filter` and `Payload`. To avoid code duplication in both tonic and actix layers, we'll handle these cases in the table of contents.

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-03-11 08:55 UTC, xzfc requested changes

2024-03-11 08:55 UTC, xzfc commented on src/actix/api/count_api.rs
> +              // ToDo: use timeout from params
Style nit: don't move this comment.

2024-03-11 08:55 UTC, xzfc commented on src/tonic/api/points_internal_api.rs
> +        let claims = request.extensions_mut().remove::<Claims>();
I suggest to put code that calls `extensions_mut().insert()` and `extensions_mut().remove()` to the same module. Then this line should look like this:

```suggestion
        let claims = super::auth::extract_claims(&mut request);
```

2024-03-15 13:05 UTC, xzfc approved these changes

2024-03-18 13:30 UTC, coszio commented
Thanks for the rebase @xzfc 🙌, I'll just do a quick refactor of `ActixClaims` into `Extension<T>` in case we want to reuse it later

2024-03-18 14:30 UTC, generall commented on src/tonic/api/points_internal_api.rs
> +use crate::tonic::auth::extract_claims;
I don't think we need Claim checks for internal API

2024-03-18 16:10 UTC, generall approved these changes

2024-03-18 16:14 UTC, merged