keep jemalloc dependency only for builds on aarch64 and amd64 platforms, fixes #2474
qdrant/qdrant pull request #3945
Opened 2024-03-31 14:20 UTC by abhishek818

Fixes: #2474 
/claim #2474 
### All Submissions:

* [X] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [X] Have you successfully ran tests with your changes locally?

2024-03-31 14:26 UTC, abhishek818 commented
@generall Up for review.

2024-03-31 14:34 UTC, Morriz commented
@generall any idea why this older (than #3946) PR is not yet approved to run tests? Does @abhishek818 need to call any other commands?

2024-03-31 14:43 UTC, generall commented
same here https://github.com/qdrant/qdrant/pull/3946#issuecomment-2028776778

2024-03-31 15:45 UTC, abhishek818 commented
@generall , have addressed your comment.

2024-03-31 16:40 UTC, abhishek818 commented
@generall  , have addressed your comment.

2024-04-01 09:25 UTC, timvisee requested changes
This does not resolve the issue, nor does it implement the suggested solution.

The original [issue](https://github.com/qdrant/qdrant/issues/2474) describes that jemalloc doesn't work on ARM64 due to an mismatch in page size. This still enables jemalloc without any changes on ARM64.

2024-04-01 09:28 UTC, timvisee requested changes
Could you enable it for PowerPC on Linux as well?

See: https://github.com/tikv/jemallocator?tab=readme-ov-file#platform-support

2024-04-01 15:34 UTC, Morriz commented on Cargo.toml
> +#['cfg(all(not(target_env = "msvc"), any(target_arch = "x86_64", target_arch = "aarch64")))'.dependencies]
@abhishek818 your logic is rather convoluted:
```py
all(not(target_env = "msvc"), any(target_arch = "x86_64", target_arch = "aarch64"))
```
as the first part becomes redundant by adding the second part. This is enough:
```py
any(target_arch = "x86_64", target_arch = "aarch64")
```

2024-04-01 15:34 UTC, Morriz commented on Cargo.toml
> +#['cfg(all(not(target_env = "msvc"), any(target_arch = "x86_64", target_arch = "aarch64")))'.dependencies]
same goes for the other instances of your logic

2024-04-01 15:38 UTC, Morriz commented
@generall like I said in https://github.com/qdrant/qdrant/pull/3946#issuecomment-2028813412, would you be ok with this PR setting the page size to 16 toes how the tests perform?

2024-04-01 15:42 UTC, generall commented
> would you be ok with this PR setting the page size to 16 to show the tests perform?

Not on this PR. We would need to test it separetelly and make sure it doesn't have negative effects

2024-04-01 15:46 UTC, Morriz commented
just trying with `JEMALLOC_SYS_WITH_LG_PAGE==16` might work (see https://github.com/tikv/jemallocator/blob/master/jemalloc-sys/README.md)

2024-04-01 15:47 UTC, generall commented
> just trying with `JEMALLOC_SYS_WITH_LG_PAGE==16` might work (see https://github.com/tikv/jemallocator/blob/master/jemalloc-sys/README.md)

I am afraid this link won't be enough to convince me. We need a proper testing on real machine

2024-04-01 15:51 UTC, Morriz commented
I presume PRs will trigger your tests? What is your concern?

2024-04-01 16:05 UTC, abhishek818 commented
@Morriz  Did some research on the with_lg_page approach, seems to be mixed opinion on this. Refer [link1 ](https://github.com/facebook/buck2/issues/91)and [link2](https://github.com/jemalloc/jemalloc/issues/467).

2024-04-01 16:27 UTC, generall commented
> I presume PRs will trigger your tests? What is your concern?


We don't have performance benchmarks for difference architectures in CI

2024-04-01 16:44 UTC, Morriz commented
@abhishek818 this PR is pointless as it does not satisfy the objective when the issue is not solved.

2024-04-01 16:45 UTC, Morriz commented
> We don't have performance benchmarks for difference architectures in CI

@generall I think we should then add such a test first?

2024-04-01 21:54 UTC, generall commented
> @generall I think we should then add such a test first?

That would be, of course, preferred. But also not very trivial, since github doesn't provide arm action runners and we would need to do something custom. So far we are only testing perf regularly on x86

2024-04-02 08:16 UTC, generall commented
Hey @abhishek818, it looks like `PowerPC` doesn't actually work. Let's rollback to just aarch and x86

2024-04-02 12:43 UTC, generall commented
@abhishek818 sorry for poking you again, but now the windows build doesn't work. I think `msvc` should not be removed

2024-04-03 09:29 UTC, timvisee approved these changes

2024-04-03 09:34 UTC, merged