gRPC API for multivector
qdrant/qdrant pull request #4068
Opened 2024-04-18 15:16 UTC by agourlay

This PR adds support for multivector in the gRPC API.

2024-04-23 08:19 UTC, generall commented on lib/api/src/grpc/proto/points.proto
> +  optional uint32 tokens_count = 3; // Number of tokens in the vector
tokens is ColBERT specific terminology. It is possible that this multi-vector functionality will be used for other purposes then ColBERT (e.g. jsut storing embeddings of multiple images of the same object), so let's call it more generic

2024-04-23 08:20 UTC, generall commented on lib/api/src/grpc/proto/points.proto
> +  optional uint32 tokens_count = 17;
let's avoid changing search API

2024-04-23 20:37 UTC, IvanPleshkov requested changes

2024-04-23 20:37 UTC, IvanPleshkov commented on lib/api/src/grpc/proto/points.proto
> +  optional uint32 tokens_count = 16;
Colbert design document covered this message and `SearchPointGroups`. The user has to send a flattened vector and `SearchPoint`/`SearchPointGroups` have to be unchanged. It's possible to convert from flattened `vector` into colbert vectors using collection DIM

2024-04-24 09:20 UTC, closed without merging

2024-04-24 09:20 UTC, agourlay commented
Thanks for the feedback, I am closing this PR because it won't be merged as is.

We have decided to not implement multivector support in search for the existing REST and gRPC API.

I will propose a new PR with the write and retrieve paths only REST and gRPC.