Make sparse vectors generic
qdrant/qdrant pull request #4364
Opened 2024-05-30 22:28 UTC by xzfc

This PR makes sparse vector types ant traits generic over the weight type.

Two implementations are provided: `half::f16` and `f32`. We'll add `u8` later since its logic significantly differs. The `half::f16` is not used anywhere yet and serves as a reference.

Only the structures from the `sparse` crate are made generic. Structures from other crates (particularly from `segment`) are still hardcoded to use `VectorElementType`/`f32`.

2024-05-30 22:33 UTC, xzfc commented on lib/segment/src/index/sparse_index/sparse_vector_index.rs
> +pub struct SparseVectorIndex<TInvertedIndex: InvertedIndex<VectorElementType>> {
Further generalization probably would start here.

2024-05-31 08:26 UTC, generall requested changes
I think we should follow the pattern of dense vector storage and _only_ change the data type inside the storage itself. We have already tried the approach with generalizing everything up to the interface, this proves to be a huge pain and not really helpful at the end.

It is fine if the input vectors will have f32 datatype, we can always convert them into f16 internally, during scoring.

2024-05-31 08:26 UTC, generall commented on lib/api/src/rest/schema.rs
> +    Sparse(sparse::common::sparse_vector::SparseVector<VectorElementType>),
I don't think we want to make `Vector` itself generic against datatype. It would require too much changes.

2024-06-08 15:57 UTC, generall approved these changes

2024-06-10 15:04 UTC, merged