universal-query: Fix lost offset in planned query conversion
qdrant/qdrant pull request #4408
Opened 2024-06-06 22:49 UTC by coszio

I realized we were sometimes ignoring `offset` when crafting the `PlannedQuery`, specifically in the case of root-level scroll-like requests. This PR fixes it and refactors it to make it (*arguably*) a little more readable

2024-06-07 15:54 UTC, generall commented on lib/collection/src/operations/universal_query/planned_query.rs
> +                    offset = req_offset;
limit of the request should be limit + offset

2024-06-07 15:55 UTC, generall commented on lib/collection/src/operations/universal_query/planned_query.rs
> +                    offset = req_offset;
same: limit + offset

2024-06-07 15:55 UTC, generall requested changes
See comments

2024-06-07 17:25 UTC, coszio commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/qdrant/qdrant/4408?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4408** <a href="https://app.graphite.dev/github/pr/qdrant/qdrant/4408?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#4407** <a href="https://app.graphite.dev/github/pr/qdrant/qdrant/4407?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4406** <a href="https://app.graphite.dev/github/pr/qdrant/qdrant/4406?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4405** <a href="https://app.graphite.dev/github/pr/qdrant/qdrant/4405?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4404** <a href="https://app.graphite.dev/github/pr/qdrant/qdrant/4404?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4380** <a href="https://app.graphite.dev/github/pr/qdrant/qdrant/4380?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4388** <a href="https://app.graphite.dev/github/pr/qdrant/qdrant/4388?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4362** <a href="https://app.graphite.dev/github/pr/qdrant/qdrant/4362?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @coszio and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-10 22:00 UTC, generall approved these changes

2024-06-10 22:06 UTC, coszio commented
### Merge activity

* **Jun 10, 6:06 PM EDT**: @coszio started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/qdrant/qdrant/4408).

2024-06-10 23:29 UTC, merged