When selecting a segment for writing, select one that has capacity
qdrant/qdrant pull request #4420
Opened 2024-06-10 12:46 UTC by timvisee

Depends on: <https://github.com/qdrant/qdrant/pull/4416>

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-06-10 21:09 UTC, generall requested changes
I think this PR is a bit more complicated than it needs to be.

I don't think SegmentHolder should know about `OptimizerThresholds`, instead it would be enough if `random_appendable_segment_with_capacity` would simply select the smallest one, even if it means we need to iterate over all of them. I am pretty sure the overhead is going to be minimal.

`aloha_random_write` In my optimion, is not required to have this logic at all. In theory it is nice to have, but as a prise we have non-trivial function with potential deadlocks doubled in size. It is only used if the segments are indexed, so not related to the case we are trying to optimize.

2024-06-11 07:17 UTC, timvisee commented
> I think this PR is a bit more complicated than it needs to be.
> 
> I don't think SegmentHolder should know about `OptimizerThresholds`, instead it would be enough if `random_appendable_segment_with_capacity` would simply select the smallest one, even if it means we need to iterate over all of them. I am pretty sure the overhead is going to be minimal.
> 
> `aloha_random_write` In my optimion, is not required to have this logic at all. In theory it is nice to have, but as a prise we have non-trivial function with potential deadlocks doubled in size. It is only used if the segments are indexed, so not related to the case we are trying to optimize.

You know what, I fully agree on it being more complicated than it needs to be. I like that the suggested approach is a lot simpler. And as I understand it it still covers the case we're actually looking for.

Now, you mention trying  to lock all segments. Since the effect of this PR is already noticeable in a simple upsertion benchmark I'm not sure I agree it is so minimal. But I'll give it a proper go anyway. We can give it a test if we like.

I'll implement your suggestion in a separate PR so that we can compare the two. This one is already quite noisy anyway.

Thanks for the suggestion and insight!

2024-06-11 07:56 UTC, timvisee commented
I've implemented the alternative here: <https://github.com/qdrant/qdrant/pull/4440>

2024-06-11 10:59 UTC, timvisee commented
Superseded by <https://github.com/qdrant/qdrant/pull/4440>

2024-06-11 10:59 UTC, closed without merging