universal-query: cluster test for query API
qdrant/qdrant pull request #4471
Opened 2024-06-14 10:16 UTC by agourlay

### All Submissions:

* [ ] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [ ] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-06-14 11:40 UTC, coszio requested changes
Good testing! I would love to also see two things more:
1. Setting read_consistency
2. Order_by in asc and desc

2024-06-14 21:15 UTC, agourlay commented
failing for scroll & query equivalence
```
scroll
{'filter': {'must_not': [{'key': 'city', 'match': {'value': 'Berlin'}}]}, 'limit': 5, 'order_by': 'count', 'direction': 'asc'}
[5, 9, 10, 6, 7]
VS
query
{'filter': {'must_not': [{'key': 'city', 'match': {'value': 'Berlin'}}]}, 'limit': 5, 'order_by': 'count', 'direction': 'asc'}
[4, 5, 6, 7, 8]
```

2024-06-17 14:39 UTC, agourlay commented
@coszio I have removed the broken scroll tests for the time being.

I propose to merge this to increase our safety net and then uncomment later the test cases when introducing a fix :)

2024-06-17 14:58 UTC, coszio approved these changes

2024-06-17 15:04 UTC, merged