Cleanup `ClusterOperations` enum structure and ser/de implementation
qdrant/qdrant pull request #4810
Opened 2024-08-02 12:11 UTC by ffuugoo

`ClusterOperations` uses `#[serde(untagged)]` in a bit of nonsensical way: each variant defines a custom structure with a single field, and this field name is unique across all structures.

Basically, it's just serde's default externally-tagged enum representation with 1) extra steps, 2) worse deserialization performance and 3) terrible error messages.

I've simplified `ClusterOperations` enum back to externally-tagged representation and moved declarations in `cluster_ops` module to be a bit more organized.

The only potential downside (stopper?) is that even if from Rust POV this new representation is exactly the same (i.e., it serializes to and deserializes from exactly the same JSON), it still changes OpenAPI spec slightly, and I'm not sure if this change would be backward compatible. 🤔

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-08-07 17:51 UTC, generall requested changes
This structure is intentional, as it generates better OpenAPI structures.
We follow this pattern in all untagged enums observed from external interfaces.

This PR breaks OpenAPI and will cause ugly anonymous objects in docs and in clients
![Screenshot from 2024-08-07 19-48-36](https://github.com/user-attachments/assets/d36aee3f-84f7-48aa-847e-dee5ba5490e0)

vs

![Screenshot from 2024-08-07 19-48-28](https://github.com/user-attachments/assets/d11f1018-f92b-4e5e-bd7b-74b043bf76d6)

2024-08-07 18:19 UTC, ffuugoo commented
> This structure is intentional, as it generates better OpenAPI structures. We follow this pattern in all untagged enums observed from external interfaces.
> 
> This PR breaks OpenAPI and will cause ugly anonymous objects in docs and in clients

Life is a prison 🥲

2024-08-08 09:36 UTC, timvisee commented
This is a painful one, OpenAPI hitting us again.

Based on the above I think we can close this. Or @ffuugoo, does this contain something else that is worth merging?

2024-08-08 09:43 UTC, ffuugoo commented
Yeah, I think we can close this for now. It's so annoying to work with this god-awful `untagged` enums. 🙄

2024-08-08 09:43 UTC, closed without merging