Add tests on uuid payload index queries with filters
qdrant/qdrant pull request #4971
Opened 2024-08-28 09:14 UTC by tellet-q

* Parameterize existing tests with different filters 
* Also add tests for query batches with and without filters.

### All Submissions:

* [X] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

2024-08-28 16:23 UTC, generall requested changes

2024-08-28 16:23 UTC, generall commented on tests/openapi/test_query_full.py
AFAIK those tests ensure consistency of results between old search API and new query API.
But they don't validate if the result itself is correct.

Since filter index shares implementation in both - old and new requests, error in the index will also be same.

let's create a test which would check against some reference output instead (or we can create test which validates that keyword and UUID indexes behave same), but I think it should be a dedicated file

2024-08-29 07:24 UTC, tellet-q commented on tests/openapi/test_query_full.py
I've added a dedicated test file that compares results between keyword index and uuid index. Right now the results for match-except filter differ between those two.

2024-08-29 08:58 UTC, tellet-q commented
Merge after https://github.com/qdrant/qdrant/pull/4977

2024-08-29 11:03 UTC, generall approved these changes

2024-08-29 11:03 UTC, merged