Drop `GraphLayersBackwardCompatibility`
qdrant/qdrant pull request #5486
Opened 2024-11-20 07:12 UTC by xzfc

This PR drops the support for reading/converting of the old `graph.bin` file format used before Qdrant 0.8.4.
This old format stores everything in a single `graph.bin` file while newer versions of qdrant store the graph in two files, `graph.bin`+`links.bin`.

2024-11-20 08:34 UTC, IvanPleshkov approved these changes

2024-11-20 08:34 UTC, IvanPleshkov commented on lib/segment/src/index/hnsw_index/graph_layers.rs
> -    links_layers: Vec<LayersContainer>,
Can you also delete please
```
pub type LayersContainer = Vec<LinkContainer>;
```
It's unused in this PR.

2024-11-20 09:40 UTC, timvisee approved these changes
Out of curiosity. What happens if a user still has this file? Will we just ignore it, or do we crash?

2024-11-20 09:45 UTC, IvanPleshkov commented
> Out of curiosity. What happens if a user still has this file? Will we just ignore it, or do we crash?
> 
> I'd prefer if we could ignore it if that isn't too much work so that we can build a fresh HNSW graph later on.

I agree with this question. We don't have a conversion from the old format. Such situations are possible even if a user updates qdrant correctly (minor-by-minor version). We probably need to implement a converter and remove everything in the next minor release. Let's discuss it. To avoid spontaneously merging before the decision, I mark this PR as changes required.

2024-11-20 09:46 UTC, IvanPleshkov requested changes
Mark as requested changes while old version support discussion

2024-11-20 09:46 UTC, timvisee commented
> Such situations are possible even if a user updates qdrant correctly (minor-by-minor version).

Good point.

2024-11-20 09:48 UTC, IvanPleshkov commented
> > Such situations are possible even if a user updates qdrant correctly (minor-by-minor version).
> 
> Good point.

I'm reading current `dev` and it seems we have conversion and we can merge this PR. @xzfc do you have a chance to check manually if the old format will work correctly?

2024-11-20 09:52 UTC, IvanPleshkov approved these changes

2024-11-26 19:16 UTC, xzfc commented
The conversion happens at `0.11.1` → `1.0.0` with the following message:
```
[segment::segment_constructor::segment_constructor_base] Migrating segment 0.4.0 -> 0.5.0
```

So, this was a dead code already.

2024-11-26 19:17 UTC, merged