Added feature to configure file path of .qdrant-initialized file
qdrant/qdrant pull request #5714
Opened 2024-12-31 11:30 UTC by jayantpranjal0

Feat: #5451

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [ ] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2025-01-01 10:35 UTC, generall commented
logic here https://github.com/qdrant/qdrant/blob/master/tools/entrypoint.sh should be updated. And overall we would need to check if this change is backward compatible. 

Overall, taking into account that the original version allowed env to overwrite the path and questionable usefulness of the whole entrypoint script, I have doubts if investing more time into this config is worth the effort

2025-01-02 09:43 UTC, timvisee requested changes
I agree with @generall.

We'd somehow have to make `entrypoint.sh` aware of the configured path. That will not be trivial.

I did leave some minor suggestions below, but that will not resolve the above problem.

2025-01-02 09:43 UTC, timvisee commented on config/config.yaml
> +init_file_path: ./.qdrant-initialized
```suggestion
init_file_path: .qdrant-initialized
```

2025-01-02 09:43 UTC, timvisee commented on src/startup.rs
>  }
Let's prefer the `QDRANT_INIT_FILE_PATH` here over the configuration file if set.

That'll ensure backwards compatibility.

2025-01-06 16:58 UTC, jayantpranjal0 commented
I agree that it wouldn't be trivial to make entrypoint.sh aware of configured init file path, but entrypoint.sh would be working as it was supposed to be working before this change, since most priority in configuration for init_file_path is given to the enviroment variable which is set in the script.

2025-01-09 16:17 UTC, jayantpranjal0 commented
@timvisee @generall how should I move forward with this issue?

2025-05-22 02:59 UTC, closed without merging