Allow to flush segment in separate thread
qdrant/qdrant pull request #927
Opened 2022-08-09 09:49 UTC by IvanPleshkov

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally using ``cargo fmt`` command prior to submission?
3. [ ] Have you checked your code using ```cargo clippy``` command?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2022-08-09 12:08 UTC, generall requested changes

2022-08-09 12:08 UTC, generall commented on lib/segment/src/segment.rs
> +            vector_storage.borrow().flush().map_err(|err| {
will panic on concurrent borrow_mut

2022-08-10 11:52 UTC, IvanPleshkov commented on lib/segment/src/segment.rs
> +            vector_storage.borrow().flush().map_err(|err| {
Fixed

2022-08-10 11:52 UTC, IvanPleshkov commented on lib/segment/src/segment.rs
> +            join_handle.join().unwrap().unwrap();
Fixed by @generall

2022-08-10 12:35 UTC, generall commented
@IvanPleshkov can you please share benchmarks result here?

2022-08-11 07:29 UTC, IvanPleshkov commented
> @IvanPleshkov can you please share benchmarks result here?

Test case: go grpc client, upsert 100.000 points without payload, dim=1000, distance=euclid. Flush interval = 5sec. I take the worst upserts.

Worst upserts in master:
```
2022/08/11 09:23:16 25.992231ms
2022/08/11 09:23:16 27.316313ms
2022/08/11 09:23:16 27.66545ms
2022/08/11 09:23:16 29.298539ms
2022/08/11 09:23:16 183.192019ms
2022/08/11 09:23:16 236.495462ms
2022/08/11 09:23:16 275.627032ms
2022/08/11 09:23:16 280.808815ms
2022/08/11 09:23:16 606.951983ms
```

Worst upserts in branch
```
2022/08/11 09:17:07 18.332058ms
2022/08/11 09:17:07 18.591699ms
2022/08/11 09:17:07 20.369265ms
2022/08/11 09:17:07 20.618688ms
2022/08/11 09:17:07 21.697782ms
2022/08/11 09:17:07 24.675179ms
2022/08/11 09:17:07 28.206836ms
2022/08/11 09:17:07 30.796368ms
```

2022-08-11 07:30 UTC, IvanPleshkov commented
Also I changed flush interval to 5sec instead of 1sec

2022-08-11 08:42 UTC, agourlay commented on lib/segment/src/segment.rs
> +            *background_flush_lock = Some(std::thread::spawn(flush_op));
Minor suggestion:

I think it is a good practice to name our threads to help us identify issues later.

```suggestion
            *background_flush_lock = Some(
              std::thread::Builder::new()
                .name("background_flush".to_string())
                .spawn(flush_op)
                .unwrap());
```

2022-08-11 08:51 UTC, agourlay commented
Are we also using `flush(false)` somewhere in the unit tests for sanity check?

2022-08-11 09:54 UTC, agourlay commented
sorry, my suggestion was not properly formatted :grimacing:

2022-08-11 10:22 UTC, IvanPleshkov commented
> sorry, my suggestion was not properly formatted 😬

fixed

2022-08-11 10:23 UTC, IvanPleshkov commented
> Are we also using `flush(false)` somewhere in the unit tests for sanity check?

That's an untrivial task because we don't have any notification about finishing background flush. What do you think @generall ?

2022-08-11 10:39 UTC, generall commented
> Are we also using flush(false) somewhere in the unit tests for sanity check?

it is used as a part of optimizer. But I think writing an explicit test should not be too complicated

2022-08-12 09:00 UTC, agourlay commented
Once I merge https://github.com/qdrant/qdrant/pull/942 you will be able to rebase and remove the remaining Clippy failures.

2022-08-15 09:47 UTC, generall approved these changes

2022-08-15 09:47 UTC, merged